# Generated by Django 4.2.6 on 2023-11-01 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_adds_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='adds',
            name='viewers',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
